spring:
  profiles:
    active: local
  kafka:
    enabled: false  # Kafka 비활성화로 시작
    bootstrap-servers: localhost:9092
    consumer:
      group-id: exchange-group-${random.uuid}  # 각 인스턴스마다 고유한 group-id 할당
    topics:
      trades: exchange.trades
    admin:
      fail-fast: false    # Kafka 연결 실패해도 애플리케이션 시작
      operation-timeout: 10000  # 10초
      close-timeout: 10000      # 10초
  redis:
    host: localhost
    port: 6379
  # JPA 공통 설정 추가
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

zookeeper:
  connect-string: localhost:2181

# Health Check & Monitoring 설정
infrastructure:
  health-check:
    enabled: true
    interval: 10000  # 5초마다 체크
    logging:
      enabled: true
      level: DEBUG  # 로깅 레벨을 DEBUG로 변경
  monitoring:
    data-flow:
      enabled: true
      logging:
        enabled: true
        level: INFO
        interval: 10000  # 10초로 통일

server:
  port: 8080

# 공통 설정
exchange:
  connection:
    max-retry-attempts: 3
    reconnect-delay: 1000      # 1초
    connection-timeout: 30000   # 30초
  websocket:
    binance: wss://stream.binance.com:9443/ws
    upbit: wss://api.upbit.com/websocket/v1
    bithumb: wss://pubwss.bithumb.com/pub/ws
  common:
    supported-symbols:
      - BTC
      - ETH
      - XRP
      - DOGE
      - USDT
  exchanges:
    binance:
      supported-currencies:
        - USDT
        - BTC
    upbit:
      supported-currencies:
        - KRW
        - BTC
        - USDT
    bithumb: 
      supported-currencies:
        - KRW    

logging:
  scheduled:
    default-interval: 10000  # 10초 (밀리초 단위)
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%logger{0}]){cyan} %clr(:){faint} %m%n"
  level:
    root: INFO
    # 데이터 흐름 관련 로깅 설정 (INFO로 변경)
    com.example.boot.exchange.layer4_distribution.kafka.service.KafkaDistributionService: INFO
    com.example.boot.exchange.layer4_distribution.direct.service.DirectDistributionService: INFO
    # 모니터링 관련 로깅 설정 (INFO로 변경)
    com.example.boot.exchange.layer4_distribution.common.monitoring: INFO
    com.example.boot.exchange.layer4_distribution.common.health: INFO
    # 기타 로깅 설정
    com.example.boot.exchange.layer4_distribution.kafka: INFO
    com.example.boot.exchange.layer4_distribution.direct: INFO
    # Kafka 관련 로깅 레벨 조정
    org.apache.kafka.clients.NetworkClient: ERROR
    org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: ERROR
    org.apache.kafka.clients.Metadata: ERROR
    org.apache.kafka: ERROR        # 전체 Kafka 로깅
    org.apache.zookeeper: ERROR    # Zookeeper 로깅
    org.apache.curator: ERROR      # Curator 로깅
    org.springframework: WARN
    # JPA SQL 로깅 추가
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # 디버깅을 위한 로깅 레벨 추가
    com.example.boot.exchange.layer5_price_cache.redis: INFO
    com.example.boot.exchange.layer5_price_cache.redis.service.RedisCacheService: WARN
    com.example.boot.exchange.layer6_analysis: DEBUG
    com.example.boot.web.websocket: DEBUG
    org.springframework.messaging: INFO
    org.springframework.web.socket: INFO

# CORS 설정
cors:
  allowed-origins: http://localhost:5173

---
# 로컬 개발 환경
spring:
  config:
    activate:
      on-profile: local
  # H2 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
cors:
  allowed-origins: http://localhost:5173

zookeeper:
  connect-string: localhost:2181

---
# Docker Compose 환경
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka:9092
  redis:
    host: redis    # localhost가 아닌 redis 컨테이너 이름
    port: 6379
  # MySQL 설정 (Docker)
  datasource:
    url: jdbc:mysql://mysql:3306/exchange?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

cors:
  allowed-origins: http://localhost:5173  # Docker 환경의 프론트엔드 주소

zookeeper:
  connect-string: zookeeper:2181

---
# EKS 운영 환경
spring:
  config:
    activate:
      on-profile: prod
  # MySQL 설정 (Production)
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate  # 운영 환경에서는 validate만 사용

cors:
  allowed-origins: ${FRONTEND_URL}  # 운영 환경의 프론트엔드 주소는 환경변수로 주입
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}

zookeeper:
  connect-string: ${ZOOKEEPER_SERVERS}



